‚óè AAA_serialLogger.service
   Loaded: not-found (Reason: Unit AAA_serialLogger.service not found.)
   Active: failed (Result: exit-code) since Wed 2021-03-17 12:42:03 EDT; 3min 30s ago
 Main PID: 18237 (code=exited, status=1/FAILURE)

Mar 17 12:42:03 raspberrypi python3[18237]: Traceback (most recent call last):
Mar 17 12:42:03 raspberrypi python3[18237]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 17 12:42:03 raspberrypi python3[18237]:     timeout=1
Mar 17 12:42:03 raspberrypi python3[18237]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 17 12:42:03 raspberrypi python3[18237]:     self.open()
Mar 17 12:42:03 raspberrypi python3[18237]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 17 12:42:03 raspberrypi python3[18237]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 17 12:42:03 raspberrypi python3[18237]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 17 12:42:03 raspberrypi systemd[1]: AAA_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 12:42:03 raspberrypi systemd[1]: AAA_serialLogger.service: Failed with result 'exit-code'.
