‚óè AAA_serialLogger.service - Service for AAA_serialLogger
   Loaded: loaded (/etc/systemd/system/AAA_serialLogger.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-03-18 17:52:14 EDT; 2s ago
 Main PID: 3332 (code=exited, status=1/FAILURE)

Mar 18 17:52:13 raspberrypi python3[3332]: Traceback (most recent call last):
Mar 18 17:52:13 raspberrypi python3[3332]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 18 17:52:13 raspberrypi python3[3332]:     timeout=1
Mar 18 17:52:13 raspberrypi python3[3332]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 18 17:52:13 raspberrypi python3[3332]:     self.open()
Mar 18 17:52:13 raspberrypi python3[3332]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 18 17:52:13 raspberrypi python3[3332]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 18 17:52:13 raspberrypi python3[3332]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 18 17:52:14 raspberrypi systemd[1]: AAA_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 17:52:14 raspberrypi systemd[1]: AAA_serialLogger.service: Failed with result 'exit-code'.
