‚óè AAB_serialLogger.service - Service for AAB_serialLogger
   Loaded: loaded (/etc/systemd/system/AAB_serialLogger.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-03-18 17:51:55 EDT; 2s ago
 Main PID: 2883 (code=exited, status=1/FAILURE)

Mar 18 17:51:55 raspberrypi python3[2883]: Traceback (most recent call last):
Mar 18 17:51:55 raspberrypi python3[2883]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 18 17:51:55 raspberrypi python3[2883]:     timeout=1
Mar 18 17:51:55 raspberrypi python3[2883]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 18 17:51:55 raspberrypi python3[2883]:     self.open()
Mar 18 17:51:55 raspberrypi python3[2883]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 18 17:51:55 raspberrypi python3[2883]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 18 17:51:55 raspberrypi python3[2883]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 18 17:51:55 raspberrypi systemd[1]: AAB_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 17:51:55 raspberrypi systemd[1]: AAB_serialLogger.service: Failed with result 'exit-code'.
