‚óè AAA_serialLogger.service - Service for AAA_serialLogger
   Loaded: loaded (/etc/systemd/system/AAA_serialLogger.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-03-17 12:42:00 EDT; 2s ago
 Main PID: 18149 (code=exited, status=1/FAILURE)

Mar 17 12:41:59 raspberrypi python3[18149]: Traceback (most recent call last):
Mar 17 12:41:59 raspberrypi python3[18149]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 17 12:41:59 raspberrypi python3[18149]:     timeout=1
Mar 17 12:41:59 raspberrypi python3[18149]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 17 12:41:59 raspberrypi python3[18149]:     self.open()
Mar 17 12:41:59 raspberrypi python3[18149]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 17 12:41:59 raspberrypi python3[18149]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 17 12:41:59 raspberrypi python3[18149]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 17 12:42:00 raspberrypi systemd[1]: AAA_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 12:42:00 raspberrypi systemd[1]: AAA_serialLogger.service: Failed with result 'exit-code'.
