‚óè AAA_serialLogger.service - Service for AAA_serialLogger
   Loaded: loaded (/etc/systemd/system/AAA_serialLogger.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-03-10 18:52:47 EST; 2s ago
 Main PID: 30988 (code=exited, status=1/FAILURE)

Mar 10 18:52:47 raspberrypi python3[30988]: Traceback (most recent call last):
Mar 10 18:52:47 raspberrypi python3[30988]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 10 18:52:47 raspberrypi python3[30988]:     timeout=1
Mar 10 18:52:47 raspberrypi python3[30988]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 10 18:52:47 raspberrypi python3[30988]:     self.open()
Mar 10 18:52:47 raspberrypi python3[30988]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 10 18:52:47 raspberrypi python3[30988]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 10 18:52:47 raspberrypi python3[30988]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 10 18:52:47 raspberrypi systemd[1]: AAA_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 18:52:47 raspberrypi systemd[1]: AAA_serialLogger.service: Failed with result 'exit-code'.
