‚óè AAB_serialLogger.service - Service for AAB_serialLogger
   Loaded: loaded (/etc/systemd/system/AAB_serialLogger.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-03-10 18:54:11 EST; 2s ago
 Main PID: 561 (code=exited, status=1/FAILURE)

Mar 10 18:54:11 raspberrypi python3[561]: Traceback (most recent call last):
Mar 10 18:54:11 raspberrypi python3[561]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 10 18:54:11 raspberrypi python3[561]:     timeout=1
Mar 10 18:54:11 raspberrypi python3[561]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 10 18:54:11 raspberrypi python3[561]:     self.open()
Mar 10 18:54:11 raspberrypi python3[561]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 10 18:54:11 raspberrypi python3[561]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 10 18:54:11 raspberrypi python3[561]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 10 18:54:11 raspberrypi systemd[1]: AAB_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 18:54:11 raspberrypi systemd[1]: AAB_serialLogger.service: Failed with result 'exit-code'.
