‚óè AAA_serialLogger.service
   Loaded: not-found (Reason: Unit AAA_serialLogger.service not found.)
   Active: failed (Result: exit-code) since Wed 2021-03-10 18:54:31 EST; 11min ago
 Main PID: 1113 (code=exited, status=1/FAILURE)

Mar 10 18:54:31 raspberrypi python3[1113]: Traceback (most recent call last):
Mar 10 18:54:31 raspberrypi python3[1113]:   File "/home/pi/serialLogger.py", line 34, in <module>
Mar 10 18:54:31 raspberrypi python3[1113]:     timeout=1
Mar 10 18:54:31 raspberrypi python3[1113]:   File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 240, in __init__
Mar 10 18:54:31 raspberrypi python3[1113]:     self.open()
Mar 10 18:54:31 raspberrypi python3[1113]:   File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 268, in open
Mar 10 18:54:31 raspberrypi python3[1113]:     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
Mar 10 18:54:31 raspberrypi python3[1113]: serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Mar 10 18:54:31 raspberrypi systemd[1]: AAA_serialLogger.service: Main process exited, code=exited, status=1/FAILURE
Mar 10 18:54:31 raspberrypi systemd[1]: AAA_serialLogger.service: Failed with result 'exit-code'.
